jobs:
    test:
        docker:
            - image: 'circleci/python:3.7.2-node'
        steps:
            - checkout
            - node/install:
                  install-npm: true
            - run: node --version
            - run: python --version
            - run: npm install
            - run: npm run linter
            - run: npm test
    deploy:
        executor: heroku/default
        steps:
            - checkout
            - heroku/install
            - heroku/deploy-via-git
orbs:
    node: circleci/node@4.1.0
    python: circleci/python@1.2.0
    heroku: circleci/heroku@1.2.2
version: 2.1
workflows:
    heroku_deploy:
        jobs:
            - test
            - deploy:
                  requires:
                      - build
