jobs:
    deploy:
        executor: heroku/default
        steps:
            - checkout
            - heroku/install
            - run:
                  command: >
                      npm install && npm test
            - heroku/deploy-via-git
orbs:
    heroku: circleci/heroku@1.2.2
version: 2.1
workflows:
    heroku_deploy:
        jobs:
            - deploy
