jobs:
    install-node:
        docker:
            - image: 'cimg/base:stable'
        steps:
            - checkout
            - node/install:
                  install-npm: true
            - run: node --version

    qa-validation:
        executor: heroku/default
        steps:
            - run: echo "Hello world"
            - run: npm run linter
            - run: npm test
    deploy:
        executor: heroku/default
        steps:
            - checkout
            - heroku/install
            - run:
                  command: >
                      npm install && npm test
            - heroku/deploy-via-git
orbs:
    node: circleci/node@4.1.0
    heroku: circleci/heroku@1.2.2
version: 2.1
workflows:
    heroku_deploy:
        jobs:
            - install-node
            - qa-validation
            - deploy
